local h_str = require "modules.h_str"
local controller = require "modules.controller_slime"
local event = require "modules.event"

go.property("hostile", true)
go.property("event_id", 0)

function init(self)
	controller.init(self)
	event.init(self)
end

function final(self)
	event.final(self)
end

function fixed_update(self, dt)
	controller.fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
	event.on_message(self, message_id, message)
end